package Items;

public enum Core {
    PHOENIX_FEATHER, DRAGON_HEARTSTRING, UNICORN_TAIL_HAIR, VEELA_HAIR, THESTRAL_TAIL_HAIR, TROLL_WHISKER, CORAL,
    DITTANY_STALK, ROUGAROU_HAIR, HORNED_SERPENT_HORN, SNALLYGASTER_HEARTSTRING, JACKALOPE_ANTLER, KNEAZLE_WHISKER,
    KELPIE_HAIR, BASILISK_HORN, AFRICAN_MERMAID_HAI, FAIRY_WING
}
